
import { Preset, PlaybackMode } from './types';

export const GRID_ROWS = 8;
export const GRID_COLS = 11;
export const TOTAL_BUTTONS = GRID_ROWS * GRID_COLS;
export const LOCAL_STORAGE_KEY = 'jingle_machine_config_v1.5_web';

export const PRESET_TEMPLATES: Preset[] = [
  {
    name: 'Radio Classica',
    config: Array.from({ length: TOTAL_BUTTONS }, (_, i) => ({
      id: i,
      name: `Jingle ${i + 1}`,
      color: '#4b5563',
      volume: 0.8,
      playbackMode: PlaybackMode.Restart,
      isLoop: false,
      crossfade: true,
      fileName: null,
      eqLow: 5,
      eqMid: 0,
      eqHigh: -5,
      pan: 0,
      solo: false,
      mute: false,
      cue: false,
      fadeInDuration: 1000,
      fadeOutDuration: 1000,
      isSpecialEffect: false,
    })),
  },
  {
    name: 'Podcast Vocale',
    config: Array.from({ length: TOTAL_BUTTONS }, (_, i) => ({
      id: i,
      name: `Voce ${i + 1}`,
      color: '#22c55e',
      volume: 1,
      playbackMode: PlaybackMode.Continue,
      isLoop: false,
      crossfade: false,
      fileName: null,
      eqLow: -5,
      eqMid: 5,
      eqHigh: 5,
      pan: 0,
      solo: false,
      mute: false,
      cue: false,
      fadeInDuration: 500,
      fadeOutDuration: 500,
      isSpecialEffect: false,
    })),
  },
  {
    name: 'DJ Elettronica',
    config: Array.from({ length: TOTAL_BUTTONS }, (_, i) => ({
      id: i,
      name: `Beat ${i + 1}`,
      color: '#8b5cf6',
      volume: 0.9,
      playbackMode: PlaybackMode.Overlay,
      isLoop: true,
      crossfade: true,
      fileName: null,
      eqLow: 10,
      eqMid: -10,
      eqHigh: 10,
      pan: i % 2 === 0 ? -0.5 : 0.5,
      solo: false,
      mute: false,
      cue: false,
      fadeInDuration: 2000,
      fadeOutDuration: 2000,
      isSpecialEffect: i >= 80, // last row special
    })),
  },
  {
    name: 'Evento Live',
    config: Array.from({ length: TOTAL_BUTTONS }, (_, i) => ({
      id: i,
      name: `Effetto ${i + 1}`,
      color: '#f97316',
      volume: 0.7,
      playbackMode: PlaybackMode.Queue,
      isLoop: false,
      crossfade: false,
      fileName: null,
      eqLow: 0,
      eqMid: 0,
      eqHigh: 0,
      pan: 0,
      solo: false,
      mute: false,
      cue: false,
      fadeInDuration: 100,
      fadeOutDuration: 100,
      isSpecialEffect: false,
    })),
  },
  {
    name: 'Emergenza',
    config: Array.from({ length: TOTAL_BUTTONS }, (_, i) => ({
      id: i,
      name: `Allarme ${i + 1}`,
      color: '#ef4444',
      volume: 1,
      playbackMode: PlaybackMode.Restart,
      isLoop: true,
      crossfade: false,
      fileName: null,
      eqLow: 20,
      eqMid: 10,
      eqHigh: 0,
      pan: 0,
      solo: false,
      mute: false,
      cue: false,
      fadeInDuration: 100,
      fadeOutDuration: 100,
      isSpecialEffect: true,
    })),
  },
];